### ISSUE TITLE
compatability issue with 2.6

### ISSUE THREAD

**Issue by calmrat** [FriendCode/funky#1]
Running setup.py install for funky
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/funky/funky.py', 230, 24, '        mapper(v): v for v in collection\n'))

it looks like an issue with compatability of generator expressions with 2.6
## THIS (no parenthesis) DOES NOT WORK

In [9]: z = lambda x: v for v in x
  File "<ipython-input-9-17cf9603ab54>", line 1
    z = lambda x: v for v in x
                      ^
SyntaxError: invalid syntax
## THIS WORKS

In [8]: z = lambda x: (v for v in x)
In [9]: z('hello')
Out[9]: <generator object <genexpr> at 0x262ffa0>

**Comment by AaronO** [comment]
The incompatibility issue wasn't caused by lambdas but instead dictionary comprehensions which were added in `Python 2.7`, I changed the it over to a generator expression that I then pass to a `dict` constructor, that produces the same effect.

I also added some examples to the README along with the install instructions, bumped the version to `0.0.2` and published it to PyPi.

We use funky internally at FriendCode (https://friendco.de), it was originally built while writing Gittle (https://github.com/FriendCode/gittle)

**Comment by calmrat** [comment]
i'm using funky vis-a-vis Gittle myself. Thanks for the fix!

**Comment by calmrat** [comment]
with latest packages on pypi ... seems all's well. Thanks again.

  Running setup.py install for funky
Successfully installed metrique metriqued dulwich funky
