### ISSUE TITLE
Browsing your code out of curiosity I think I spotted a typo

### ISSUE THREAD

**Issue by mbirtwell** [FriendCode/funky#3]
On this line https://github.com/FriendCode/funky/blob/master/funky/funky.py#L173 I think you meant timestamps.

**Comment by AaronO** [comment]
@mbirtwell Well spotted, thanks ! :+1: 

I think this went unnoticed since we used `.clear()` (to delete all entries).

And most importantly we aren't actively using this code any more, Python is awesome and functional programming is as well (that's how I tend to program), but these days we're building [GitBook](https://www.gitbook.com) where we're using a mix of `node.js` and `go` (`golang`).
